package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessSampleinput;
import com.cibr.animal.demo.entity.CibrTaskProcessSampleinputExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CibrTaskProcessSampleinputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessSampleinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessSampleinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessSampleinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessSampleinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    List<CibrTaskProcessSampleinput> selectByExample(CibrTaskProcessSampleinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    CibrTaskProcessSampleinput selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessSampleinput record, @Param("example") CibrTaskProcessSampleinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessSampleinput record, @Param("example") CibrTaskProcessSampleinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessSampleinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessSampleinput record);
}