package com.cibr.animal.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrTaskProcessSampleinputExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public CibrTaskProcessSampleinputExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNull() {
            addCriterion("processId is null");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNotNull() {
            addCriterion("processId is not null");
            return (Criteria) this;
        }

        public Criteria andProcessidEqualTo(String value) {
            addCriterion("processId =", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotEqualTo(String value) {
            addCriterion("processId <>", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThan(String value) {
            addCriterion("processId >", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThanOrEqualTo(String value) {
            addCriterion("processId >=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThan(String value) {
            addCriterion("processId <", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThanOrEqualTo(String value) {
            addCriterion("processId <=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLike(String value) {
            addCriterion("processId like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotLike(String value) {
            addCriterion("processId not like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidIn(List<String> values) {
            addCriterion("processId in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotIn(List<String> values) {
            addCriterion("processId not in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidBetween(String value1, String value2) {
            addCriterion("processId between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotBetween(String value1, String value2) {
            addCriterion("processId not between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andSamplenameIsNull() {
            addCriterion("sampleName is null");
            return (Criteria) this;
        }

        public Criteria andSamplenameIsNotNull() {
            addCriterion("sampleName is not null");
            return (Criteria) this;
        }

        public Criteria andSamplenameEqualTo(String value) {
            addCriterion("sampleName =", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotEqualTo(String value) {
            addCriterion("sampleName <>", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameGreaterThan(String value) {
            addCriterion("sampleName >", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameGreaterThanOrEqualTo(String value) {
            addCriterion("sampleName >=", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLessThan(String value) {
            addCriterion("sampleName <", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLessThanOrEqualTo(String value) {
            addCriterion("sampleName <=", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLike(String value) {
            addCriterion("sampleName like", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotLike(String value) {
            addCriterion("sampleName not like", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameIn(List<String> values) {
            addCriterion("sampleName in", values, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotIn(List<String> values) {
            addCriterion("sampleName not in", values, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameBetween(String value1, String value2) {
            addCriterion("sampleName between", value1, value2, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotBetween(String value1, String value2) {
            addCriterion("sampleName not between", value1, value2, "samplename");
            return (Criteria) this;
        }

        public Criteria andSpeciesIsNull() {
            addCriterion("species is null");
            return (Criteria) this;
        }

        public Criteria andSpeciesIsNotNull() {
            addCriterion("species is not null");
            return (Criteria) this;
        }

        public Criteria andSpeciesEqualTo(String value) {
            addCriterion("species =", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesNotEqualTo(String value) {
            addCriterion("species <>", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesGreaterThan(String value) {
            addCriterion("species >", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesGreaterThanOrEqualTo(String value) {
            addCriterion("species >=", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesLessThan(String value) {
            addCriterion("species <", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesLessThanOrEqualTo(String value) {
            addCriterion("species <=", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesLike(String value) {
            addCriterion("species like", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesNotLike(String value) {
            addCriterion("species not like", value, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesIn(List<String> values) {
            addCriterion("species in", values, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesNotIn(List<String> values) {
            addCriterion("species not in", values, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesBetween(String value1, String value2) {
            addCriterion("species between", value1, value2, "species");
            return (Criteria) this;
        }

        public Criteria andSpeciesNotBetween(String value1, String value2) {
            addCriterion("species not between", value1, value2, "species");
            return (Criteria) this;
        }

        public Criteria andTissueIsNull() {
            addCriterion("tissue is null");
            return (Criteria) this;
        }

        public Criteria andTissueIsNotNull() {
            addCriterion("tissue is not null");
            return (Criteria) this;
        }

        public Criteria andTissueEqualTo(String value) {
            addCriterion("tissue =", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueNotEqualTo(String value) {
            addCriterion("tissue <>", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueGreaterThan(String value) {
            addCriterion("tissue >", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueGreaterThanOrEqualTo(String value) {
            addCriterion("tissue >=", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueLessThan(String value) {
            addCriterion("tissue <", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueLessThanOrEqualTo(String value) {
            addCriterion("tissue <=", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueLike(String value) {
            addCriterion("tissue like", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueNotLike(String value) {
            addCriterion("tissue not like", value, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueIn(List<String> values) {
            addCriterion("tissue in", values, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueNotIn(List<String> values) {
            addCriterion("tissue not in", values, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueBetween(String value1, String value2) {
            addCriterion("tissue between", value1, value2, "tissue");
            return (Criteria) this;
        }

        public Criteria andTissueNotBetween(String value1, String value2) {
            addCriterion("tissue not between", value1, value2, "tissue");
            return (Criteria) this;
        }

        public Criteria andSamplemsgIsNull() {
            addCriterion("sampleMsg is null");
            return (Criteria) this;
        }

        public Criteria andSamplemsgIsNotNull() {
            addCriterion("sampleMsg is not null");
            return (Criteria) this;
        }

        public Criteria andSamplemsgEqualTo(String value) {
            addCriterion("sampleMsg =", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgNotEqualTo(String value) {
            addCriterion("sampleMsg <>", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgGreaterThan(String value) {
            addCriterion("sampleMsg >", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgGreaterThanOrEqualTo(String value) {
            addCriterion("sampleMsg >=", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgLessThan(String value) {
            addCriterion("sampleMsg <", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgLessThanOrEqualTo(String value) {
            addCriterion("sampleMsg <=", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgLike(String value) {
            addCriterion("sampleMsg like", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgNotLike(String value) {
            addCriterion("sampleMsg not like", value, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgIn(List<String> values) {
            addCriterion("sampleMsg in", values, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgNotIn(List<String> values) {
            addCriterion("sampleMsg not in", values, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgBetween(String value1, String value2) {
            addCriterion("sampleMsg between", value1, value2, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplemsgNotBetween(String value1, String value2) {
            addCriterion("sampleMsg not between", value1, value2, "samplemsg");
            return (Criteria) this;
        }

        public Criteria andSamplestatuIsNull() {
            addCriterion("sampleStatu is null");
            return (Criteria) this;
        }

        public Criteria andSamplestatuIsNotNull() {
            addCriterion("sampleStatu is not null");
            return (Criteria) this;
        }

        public Criteria andSamplestatuEqualTo(String value) {
            addCriterion("sampleStatu =", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuNotEqualTo(String value) {
            addCriterion("sampleStatu <>", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuGreaterThan(String value) {
            addCriterion("sampleStatu >", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuGreaterThanOrEqualTo(String value) {
            addCriterion("sampleStatu >=", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuLessThan(String value) {
            addCriterion("sampleStatu <", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuLessThanOrEqualTo(String value) {
            addCriterion("sampleStatu <=", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuLike(String value) {
            addCriterion("sampleStatu like", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuNotLike(String value) {
            addCriterion("sampleStatu not like", value, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuIn(List<String> values) {
            addCriterion("sampleStatu in", values, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuNotIn(List<String> values) {
            addCriterion("sampleStatu not in", values, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuBetween(String value1, String value2) {
            addCriterion("sampleStatu between", value1, value2, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andSamplestatuNotBetween(String value1, String value2) {
            addCriterion("sampleStatu not between", value1, value2, "samplestatu");
            return (Criteria) this;
        }

        public Criteria andTissuenumberIsNull() {
            addCriterion("tissueNumber is null");
            return (Criteria) this;
        }

        public Criteria andTissuenumberIsNotNull() {
            addCriterion("tissueNumber is not null");
            return (Criteria) this;
        }

        public Criteria andTissuenumberEqualTo(String value) {
            addCriterion("tissueNumber =", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberNotEqualTo(String value) {
            addCriterion("tissueNumber <>", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberGreaterThan(String value) {
            addCriterion("tissueNumber >", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberGreaterThanOrEqualTo(String value) {
            addCriterion("tissueNumber >=", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberLessThan(String value) {
            addCriterion("tissueNumber <", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberLessThanOrEqualTo(String value) {
            addCriterion("tissueNumber <=", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberLike(String value) {
            addCriterion("tissueNumber like", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberNotLike(String value) {
            addCriterion("tissueNumber not like", value, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberIn(List<String> values) {
            addCriterion("tissueNumber in", values, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberNotIn(List<String> values) {
            addCriterion("tissueNumber not in", values, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberBetween(String value1, String value2) {
            addCriterion("tissueNumber between", value1, value2, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andTissuenumberNotBetween(String value1, String value2) {
            addCriterion("tissueNumber not between", value1, value2, "tissuenumber");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeIsNull() {
            addCriterion("bloodVolume is null");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeIsNotNull() {
            addCriterion("bloodVolume is not null");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeEqualTo(String value) {
            addCriterion("bloodVolume =", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeNotEqualTo(String value) {
            addCriterion("bloodVolume <>", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeGreaterThan(String value) {
            addCriterion("bloodVolume >", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeGreaterThanOrEqualTo(String value) {
            addCriterion("bloodVolume >=", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeLessThan(String value) {
            addCriterion("bloodVolume <", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeLessThanOrEqualTo(String value) {
            addCriterion("bloodVolume <=", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeLike(String value) {
            addCriterion("bloodVolume like", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeNotLike(String value) {
            addCriterion("bloodVolume not like", value, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeIn(List<String> values) {
            addCriterion("bloodVolume in", values, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeNotIn(List<String> values) {
            addCriterion("bloodVolume not in", values, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeBetween(String value1, String value2) {
            addCriterion("bloodVolume between", value1, value2, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andBloodvolumeNotBetween(String value1, String value2) {
            addCriterion("bloodVolume not between", value1, value2, "bloodvolume");
            return (Criteria) this;
        }

        public Criteria andConcentrationIsNull() {
            addCriterion("concentration is null");
            return (Criteria) this;
        }

        public Criteria andConcentrationIsNotNull() {
            addCriterion("concentration is not null");
            return (Criteria) this;
        }

        public Criteria andConcentrationEqualTo(String value) {
            addCriterion("concentration =", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationNotEqualTo(String value) {
            addCriterion("concentration <>", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationGreaterThan(String value) {
            addCriterion("concentration >", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationGreaterThanOrEqualTo(String value) {
            addCriterion("concentration >=", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationLessThan(String value) {
            addCriterion("concentration <", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationLessThanOrEqualTo(String value) {
            addCriterion("concentration <=", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationLike(String value) {
            addCriterion("concentration like", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationNotLike(String value) {
            addCriterion("concentration not like", value, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationIn(List<String> values) {
            addCriterion("concentration in", values, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationNotIn(List<String> values) {
            addCriterion("concentration not in", values, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationBetween(String value1, String value2) {
            addCriterion("concentration between", value1, value2, "concentration");
            return (Criteria) this;
        }

        public Criteria andConcentrationNotBetween(String value1, String value2) {
            addCriterion("concentration not between", value1, value2, "concentration");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeIsNull() {
            addCriterion("sampleVolume is null");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeIsNotNull() {
            addCriterion("sampleVolume is not null");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeEqualTo(String value) {
            addCriterion("sampleVolume =", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeNotEqualTo(String value) {
            addCriterion("sampleVolume <>", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeGreaterThan(String value) {
            addCriterion("sampleVolume >", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeGreaterThanOrEqualTo(String value) {
            addCriterion("sampleVolume >=", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeLessThan(String value) {
            addCriterion("sampleVolume <", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeLessThanOrEqualTo(String value) {
            addCriterion("sampleVolume <=", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeLike(String value) {
            addCriterion("sampleVolume like", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeNotLike(String value) {
            addCriterion("sampleVolume not like", value, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeIn(List<String> values) {
            addCriterion("sampleVolume in", values, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeNotIn(List<String> values) {
            addCriterion("sampleVolume not in", values, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeBetween(String value1, String value2) {
            addCriterion("sampleVolume between", value1, value2, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andSamplevolumeNotBetween(String value1, String value2) {
            addCriterion("sampleVolume not between", value1, value2, "samplevolume");
            return (Criteria) this;
        }

        public Criteria andTotalnumberIsNull() {
            addCriterion("totalNumber is null");
            return (Criteria) this;
        }

        public Criteria andTotalnumberIsNotNull() {
            addCriterion("totalNumber is not null");
            return (Criteria) this;
        }

        public Criteria andTotalnumberEqualTo(String value) {
            addCriterion("totalNumber =", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberNotEqualTo(String value) {
            addCriterion("totalNumber <>", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberGreaterThan(String value) {
            addCriterion("totalNumber >", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberGreaterThanOrEqualTo(String value) {
            addCriterion("totalNumber >=", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberLessThan(String value) {
            addCriterion("totalNumber <", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberLessThanOrEqualTo(String value) {
            addCriterion("totalNumber <=", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberLike(String value) {
            addCriterion("totalNumber like", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberNotLike(String value) {
            addCriterion("totalNumber not like", value, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberIn(List<String> values) {
            addCriterion("totalNumber in", values, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberNotIn(List<String> values) {
            addCriterion("totalNumber not in", values, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberBetween(String value1, String value2) {
            addCriterion("totalNumber between", value1, value2, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andTotalnumberNotBetween(String value1, String value2) {
            addCriterion("totalNumber not between", value1, value2, "totalnumber");
            return (Criteria) this;
        }

        public Criteria andCelllifeIsNull() {
            addCriterion("cellLife is null");
            return (Criteria) this;
        }

        public Criteria andCelllifeIsNotNull() {
            addCriterion("cellLife is not null");
            return (Criteria) this;
        }

        public Criteria andCelllifeEqualTo(String value) {
            addCriterion("cellLife =", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeNotEqualTo(String value) {
            addCriterion("cellLife <>", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeGreaterThan(String value) {
            addCriterion("cellLife >", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeGreaterThanOrEqualTo(String value) {
            addCriterion("cellLife >=", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeLessThan(String value) {
            addCriterion("cellLife <", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeLessThanOrEqualTo(String value) {
            addCriterion("cellLife <=", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeLike(String value) {
            addCriterion("cellLife like", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeNotLike(String value) {
            addCriterion("cellLife not like", value, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeIn(List<String> values) {
            addCriterion("cellLife in", values, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeNotIn(List<String> values) {
            addCriterion("cellLife not in", values, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeBetween(String value1, String value2) {
            addCriterion("cellLife between", value1, value2, "celllife");
            return (Criteria) this;
        }

        public Criteria andCelllifeNotBetween(String value1, String value2) {
            addCriterion("cellLife not between", value1, value2, "celllife");
            return (Criteria) this;
        }

        public Criteria andCellsortIsNull() {
            addCriterion("cellSort is null");
            return (Criteria) this;
        }

        public Criteria andCellsortIsNotNull() {
            addCriterion("cellSort is not null");
            return (Criteria) this;
        }

        public Criteria andCellsortEqualTo(String value) {
            addCriterion("cellSort =", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortNotEqualTo(String value) {
            addCriterion("cellSort <>", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortGreaterThan(String value) {
            addCriterion("cellSort >", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortGreaterThanOrEqualTo(String value) {
            addCriterion("cellSort >=", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortLessThan(String value) {
            addCriterion("cellSort <", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortLessThanOrEqualTo(String value) {
            addCriterion("cellSort <=", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortLike(String value) {
            addCriterion("cellSort like", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortNotLike(String value) {
            addCriterion("cellSort not like", value, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortIn(List<String> values) {
            addCriterion("cellSort in", values, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortNotIn(List<String> values) {
            addCriterion("cellSort not in", values, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortBetween(String value1, String value2) {
            addCriterion("cellSort between", value1, value2, "cellsort");
            return (Criteria) this;
        }

        public Criteria andCellsortNotBetween(String value1, String value2) {
            addCriterion("cellSort not between", value1, value2, "cellsort");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeIsNull() {
            addCriterion("databaseType is null");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeIsNotNull() {
            addCriterion("databaseType is not null");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeEqualTo(String value) {
            addCriterion("databaseType =", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeNotEqualTo(String value) {
            addCriterion("databaseType <>", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeGreaterThan(String value) {
            addCriterion("databaseType >", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeGreaterThanOrEqualTo(String value) {
            addCriterion("databaseType >=", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeLessThan(String value) {
            addCriterion("databaseType <", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeLessThanOrEqualTo(String value) {
            addCriterion("databaseType <=", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeLike(String value) {
            addCriterion("databaseType like", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeNotLike(String value) {
            addCriterion("databaseType not like", value, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeIn(List<String> values) {
            addCriterion("databaseType in", values, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeNotIn(List<String> values) {
            addCriterion("databaseType not in", values, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeBetween(String value1, String value2) {
            addCriterion("databaseType between", value1, value2, "databasetype");
            return (Criteria) this;
        }

        public Criteria andDatabasetypeNotBetween(String value1, String value2) {
            addCriterion("databaseType not between", value1, value2, "databasetype");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformIsNull() {
            addCriterion("SequencingPlatform is null");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformIsNotNull() {
            addCriterion("SequencingPlatform is not null");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformEqualTo(String value) {
            addCriterion("SequencingPlatform =", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformNotEqualTo(String value) {
            addCriterion("SequencingPlatform <>", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformGreaterThan(String value) {
            addCriterion("SequencingPlatform >", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformGreaterThanOrEqualTo(String value) {
            addCriterion("SequencingPlatform >=", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformLessThan(String value) {
            addCriterion("SequencingPlatform <", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformLessThanOrEqualTo(String value) {
            addCriterion("SequencingPlatform <=", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformLike(String value) {
            addCriterion("SequencingPlatform like", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformNotLike(String value) {
            addCriterion("SequencingPlatform not like", value, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformIn(List<String> values) {
            addCriterion("SequencingPlatform in", values, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformNotIn(List<String> values) {
            addCriterion("SequencingPlatform not in", values, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformBetween(String value1, String value2) {
            addCriterion("SequencingPlatform between", value1, value2, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andSequencingplatformNotBetween(String value1, String value2) {
            addCriterion("SequencingPlatform not between", value1, value2, "sequencingplatform");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIsNull() {
            addCriterion("currentStatu is null");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIsNotNull() {
            addCriterion("currentStatu is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuEqualTo(String value) {
            addCriterion("currentStatu =", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotEqualTo(String value) {
            addCriterion("currentStatu <>", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuGreaterThan(String value) {
            addCriterion("currentStatu >", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuGreaterThanOrEqualTo(String value) {
            addCriterion("currentStatu >=", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLessThan(String value) {
            addCriterion("currentStatu <", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLessThanOrEqualTo(String value) {
            addCriterion("currentStatu <=", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLike(String value) {
            addCriterion("currentStatu like", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotLike(String value) {
            addCriterion("currentStatu not like", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIn(List<String> values) {
            addCriterion("currentStatu in", values, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotIn(List<String> values) {
            addCriterion("currentStatu not in", values, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuBetween(String value1, String value2) {
            addCriterion("currentStatu between", value1, value2, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotBetween(String value1, String value2) {
            addCriterion("currentStatu not between", value1, value2, "currentstatu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_sampleinput
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}