package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskProcessSampleinput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.sampleName
     *
     * @mbggenerated
     */
    private String samplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.species
     *
     * @mbggenerated
     */
    private String species;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.tissue
     *
     * @mbggenerated
     */
    private String tissue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.sampleMsg
     *
     * @mbggenerated
     */
    private String samplemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.sampleStatu
     *
     * @mbggenerated
     */
    private String samplestatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.tissueNumber
     *
     * @mbggenerated
     */
    private String tissuenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.bloodVolume
     *
     * @mbggenerated
     */
    private String bloodvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.concentration
     *
     * @mbggenerated
     */
    private String concentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.sampleVolume
     *
     * @mbggenerated
     */
    private String samplevolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.totalNumber
     *
     * @mbggenerated
     */
    private String totalnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.cellLife
     *
     * @mbggenerated
     */
    private String celllife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.cellSort
     *
     * @mbggenerated
     */
    private String cellsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.databaseType
     *
     * @mbggenerated
     */
    private String databasetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.SequencingPlatform
     *
     * @mbggenerated
     */
    private String sequencingplatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_sampleinput.currentStatu
     *
     * @mbggenerated
     */
    private String currentstatu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.id
     *
     * @return the value of cibr_task_process_sampleinput.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.id
     *
     * @param id the value for cibr_task_process_sampleinput.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.processId
     *
     * @return the value of cibr_task_process_sampleinput.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.processId
     *
     * @param processid the value for cibr_task_process_sampleinput.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.sampleName
     *
     * @return the value of cibr_task_process_sampleinput.sampleName
     *
     * @mbggenerated
     */
    public String getSamplename() {
        return samplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.sampleName
     *
     * @param samplename the value for cibr_task_process_sampleinput.sampleName
     *
     * @mbggenerated
     */
    public void setSamplename(String samplename) {
        this.samplename = samplename == null ? null : samplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.species
     *
     * @return the value of cibr_task_process_sampleinput.species
     *
     * @mbggenerated
     */
    public String getSpecies() {
        return species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.species
     *
     * @param species the value for cibr_task_process_sampleinput.species
     *
     * @mbggenerated
     */
    public void setSpecies(String species) {
        this.species = species == null ? null : species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.tissue
     *
     * @return the value of cibr_task_process_sampleinput.tissue
     *
     * @mbggenerated
     */
    public String getTissue() {
        return tissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.tissue
     *
     * @param tissue the value for cibr_task_process_sampleinput.tissue
     *
     * @mbggenerated
     */
    public void setTissue(String tissue) {
        this.tissue = tissue == null ? null : tissue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.sampleMsg
     *
     * @return the value of cibr_task_process_sampleinput.sampleMsg
     *
     * @mbggenerated
     */
    public String getSamplemsg() {
        return samplemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.sampleMsg
     *
     * @param samplemsg the value for cibr_task_process_sampleinput.sampleMsg
     *
     * @mbggenerated
     */
    public void setSamplemsg(String samplemsg) {
        this.samplemsg = samplemsg == null ? null : samplemsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.sampleStatu
     *
     * @return the value of cibr_task_process_sampleinput.sampleStatu
     *
     * @mbggenerated
     */
    public String getSamplestatu() {
        return samplestatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.sampleStatu
     *
     * @param samplestatu the value for cibr_task_process_sampleinput.sampleStatu
     *
     * @mbggenerated
     */
    public void setSamplestatu(String samplestatu) {
        this.samplestatu = samplestatu == null ? null : samplestatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.tissueNumber
     *
     * @return the value of cibr_task_process_sampleinput.tissueNumber
     *
     * @mbggenerated
     */
    public String getTissuenumber() {
        return tissuenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.tissueNumber
     *
     * @param tissuenumber the value for cibr_task_process_sampleinput.tissueNumber
     *
     * @mbggenerated
     */
    public void setTissuenumber(String tissuenumber) {
        this.tissuenumber = tissuenumber == null ? null : tissuenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.bloodVolume
     *
     * @return the value of cibr_task_process_sampleinput.bloodVolume
     *
     * @mbggenerated
     */
    public String getBloodvolume() {
        return bloodvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.bloodVolume
     *
     * @param bloodvolume the value for cibr_task_process_sampleinput.bloodVolume
     *
     * @mbggenerated
     */
    public void setBloodvolume(String bloodvolume) {
        this.bloodvolume = bloodvolume == null ? null : bloodvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.concentration
     *
     * @return the value of cibr_task_process_sampleinput.concentration
     *
     * @mbggenerated
     */
    public String getConcentration() {
        return concentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.concentration
     *
     * @param concentration the value for cibr_task_process_sampleinput.concentration
     *
     * @mbggenerated
     */
    public void setConcentration(String concentration) {
        this.concentration = concentration == null ? null : concentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.sampleVolume
     *
     * @return the value of cibr_task_process_sampleinput.sampleVolume
     *
     * @mbggenerated
     */
    public String getSamplevolume() {
        return samplevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.sampleVolume
     *
     * @param samplevolume the value for cibr_task_process_sampleinput.sampleVolume
     *
     * @mbggenerated
     */
    public void setSamplevolume(String samplevolume) {
        this.samplevolume = samplevolume == null ? null : samplevolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.totalNumber
     *
     * @return the value of cibr_task_process_sampleinput.totalNumber
     *
     * @mbggenerated
     */
    public String getTotalnumber() {
        return totalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.totalNumber
     *
     * @param totalnumber the value for cibr_task_process_sampleinput.totalNumber
     *
     * @mbggenerated
     */
    public void setTotalnumber(String totalnumber) {
        this.totalnumber = totalnumber == null ? null : totalnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.cellLife
     *
     * @return the value of cibr_task_process_sampleinput.cellLife
     *
     * @mbggenerated
     */
    public String getCelllife() {
        return celllife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.cellLife
     *
     * @param celllife the value for cibr_task_process_sampleinput.cellLife
     *
     * @mbggenerated
     */
    public void setCelllife(String celllife) {
        this.celllife = celllife == null ? null : celllife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.cellSort
     *
     * @return the value of cibr_task_process_sampleinput.cellSort
     *
     * @mbggenerated
     */
    public String getCellsort() {
        return cellsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.cellSort
     *
     * @param cellsort the value for cibr_task_process_sampleinput.cellSort
     *
     * @mbggenerated
     */
    public void setCellsort(String cellsort) {
        this.cellsort = cellsort == null ? null : cellsort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.databaseType
     *
     * @return the value of cibr_task_process_sampleinput.databaseType
     *
     * @mbggenerated
     */
    public String getDatabasetype() {
        return databasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.databaseType
     *
     * @param databasetype the value for cibr_task_process_sampleinput.databaseType
     *
     * @mbggenerated
     */
    public void setDatabasetype(String databasetype) {
        this.databasetype = databasetype == null ? null : databasetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.SequencingPlatform
     *
     * @return the value of cibr_task_process_sampleinput.SequencingPlatform
     *
     * @mbggenerated
     */
    public String getSequencingplatform() {
        return sequencingplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.SequencingPlatform
     *
     * @param sequencingplatform the value for cibr_task_process_sampleinput.SequencingPlatform
     *
     * @mbggenerated
     */
    public void setSequencingplatform(String sequencingplatform) {
        this.sequencingplatform = sequencingplatform == null ? null : sequencingplatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.remarks
     *
     * @return the value of cibr_task_process_sampleinput.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.remarks
     *
     * @param remarks the value for cibr_task_process_sampleinput.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.creater
     *
     * @return the value of cibr_task_process_sampleinput.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.creater
     *
     * @param creater the value for cibr_task_process_sampleinput.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.createTime
     *
     * @return the value of cibr_task_process_sampleinput.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.createTime
     *
     * @param createtime the value for cibr_task_process_sampleinput.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_sampleinput.currentStatu
     *
     * @return the value of cibr_task_process_sampleinput.currentStatu
     *
     * @mbggenerated
     */
    public String getCurrentstatu() {
        return currentstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_sampleinput.currentStatu
     *
     * @param currentstatu the value for cibr_task_process_sampleinput.currentStatu
     *
     * @mbggenerated
     */
    public void setCurrentstatu(String currentstatu) {
        this.currentstatu = currentstatu == null ? null : currentstatu.trim();
    }
}